name: Build Windows EXE

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Install MinGW
      uses: egor-tensin/setup-mingw@v2
      with:
        platform: x64

    - name: Compile C++ project
      run: |
        g++ cerberus.cpp -o cerberus.exe -std=c++17 -lpsapi -lwininet -lws2_32 -I.
    
    - name: Upload built EXE
      uses: actions/upload-artifact@v4
      with:
        name: cerberus-exe
        path: cerberus.exe
