name: build-windows

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Install MinGW
      uses: egor-tensin/setup-mingw@v2
      with:
        version: 12.2.0
        platform: x64

    - name: Compile C++ project
      run: |
        g++ cerberus.cpp -o cerberus.exe -std=c++17 -lpsapi -lwininet -lws2_32

    - name: Upload built EXE
      uses: actions/upload-artifact@v3
      with:
        name: cerberus-exe
        path: cerberus.exe
