name: Build Windows EXE

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install MSYS2 and MinGW-w64
      uses: msys2/setup-msys2@v2
      with:
        install: mingw-w64-x86_64-gcc

    - name: Compile project
      shell: msys2 {0}
      run: |
        g++ cerberus.cpp -o cerberus.exe -std=c++17 -lpsapi -lwininet -lws2_32 -I.

    - name: Upload built EXE
      uses: actions/upload-artifact@v4
      with:
        name: cerberus-exe
        path: cerberus.exe
